name: 'Keploy TestRun Report'
description: "A action to run e2e test run"
author: Alphasians
branding:
  icon: 'activity'
  color: 'orange'

inputs:
  working-directory:
    description: Relative path under $GITHUB_WORKSPACE where the repository was checked out
    required: true
  delay:
    description: Delay between each test cases
    required: false
    default: 20
  command:
    description: Command to run the application
    required: true
  keploy-path:
    description: Path to keploy
    required: true
    default: ./
outputs:
  test-report:
    description: Keploy Test report
  success:
    description: Count of passed tests
  failed:
    description: Count of failed tests

runs:
  using: "composite"
  steps:
  - name: Setup GITHUB_PATH for script
    run: |
      echo "${{ github.action_path }}" >> $GITHUB_PATH
      echo "${{ inputs.working-directory }}"
    shell: bash
  - name: Grant permissions
    run: chmod +x ${GITHUB_ACTION_PATH}/install.sh
    shell: sh
  - id: keploy-test-report
    name: Run Script
    run:  |
      ${GITHUB_ACTION_PATH}/install.sh
      echo "No. of TestSets is $(find . -type d -name 'test-set-*' | wc -l)" >> ${GITHUB_WORKSPACE}/${WORKDIR}/temp1.yml
      cd ${GITHUB_WORKSPACE}/${WORKDIR}/keploy/testReports
      ls
      echo "No. of Reports is $(find "$@" -type f | wc -l)" >> ${GITHUB_WORKSPACE}/${WORKDIR}/temp.yml
      cat ${GITHUB_WORKSPACE}/${WORKDIR}/temp.yml
      cat ${GITHUB_WORKSPACE}/${WORKDIR}/temp1.yml
      
    shell: sh
    env:
      WORKDIR: ${{ inputs.working-directory }}
      DELAY: ${{ inputs.delay }}
      COMMAND : ${{ inputs.command }}
      KEPLOY_PATH: ${{inputs.keploy-path}}
