name: Vaunt Cards Update
on:
  push:
    branches:
      - main

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Update Cards
      uses: Alphasians/test-reportql@main